name: bike-rental-service-ev

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - service-ev-net
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - service-ev-net

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - service-ev-net
    ports:
      - "9090:9090"
    expose:
      - 9090
  bike-manager:
    image: bike-manager
    restart: always
    container_name: bike-manager-01
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - service-ev-net
    ports:
      - "9091:8080"
    expose:
      - 9091
  account-manager:
    image: account-manager
    restart: always
    container_name: account-manager-01
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - service-ev-net
    ports:
      - "9092:8080"
    expose:
      - 9092
  ride-manager:
    image: ride-manager
    restart: always
    container_name: ride-manager-01
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - service-ev-net
    ports:
      - "9093:8080"
    expose:
      - 9093
  auth-service:
    image: auth-service
    restart: always
    container_name: auth-service-01
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - service-ev-net
    ports:
      - "9094:8080"
    expose:
      - 9094
  api-gateway:
    image: api-gateway
    restart: always
    container_name: api-gateway-01
    networks:
      - service-ev-net
    ports:
      - "8080:8080"
    expose:
      - 8080
networks:
  service-ev-net:
    driver: bridge