global:
  scrape_interval: 5s
scrape_configs:
 - job_name: service-metrics
   static_configs:
    - targets:
       - bike-manager:8080
       - account-manager:8080
       - ride-manager:8080
       - auth-service:8080
