apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: bike-rental-service-ev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bike-rental-service-ev
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
    - job_name: service-metrics
      static_configs:
        - targets:
          - bike-manager:8080
          - account-manager:8080
          - ride-manager:8080
          - auth-service:8080

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: bike-rental-service-ev
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
