apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-manager
  namespace: bike-rental-service-ev
spec:
  selector:
    matchLabels:
      app: ride-manager
  template:
    metadata:
      labels:
        app: ride-manager
    spec:
      containers:
      - name: ride-manager
        image: ride-manager
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: ride-manager
  namespace: bike-rental-service-ev
spec:
  selector:
    app: ride-manager
  ports:
  - port: 8080